
drop table L3_INFO @

create TABLE L3_INFO (
L3 VARCHAR(64) NOT NULL, 
L3TYPE VARCHAR(64), 
REGION VARCHAR(64), 
L4 VARCHAR(64), 
OPSTATE_D1 VARCHAR(64), 
OPSTATE_D2 VARCHAR(64), 
OPSTATE_D3 VARCHAR(64), 
GEO_LOCATION VARCHAR(64), 
GEO_AREA VARCHAR(64), 
GEO_COORDINATES VARCHAR(64), 
ACCESS VARCHAR(128),
PRIORITY VARCHAR(32),
BUSINESS_QUALIFIER1 VARCHAR(64),
BUSINESS_QUALIFIER2 VARCHAR(64),
BUSINESS_QUALIFIER3 VARCHAR(64),
BUSINESS_QUALIFIER4 VARCHAR(64),
PRIMARY KEY (L3)
) @

create or replace procedure populate_l3_info () 
LANGUAGE SQL
BEGIN
DECLARE v_L3 VARCHAR(64) ; 
DECLARE v_L3TYPE VARCHAR(64); 
DECLARE v_REGION VARCHAR(64); 
DECLARE v_L4 VARCHAR(64); 
DECLARE v_OPSTATE_D1 VARCHAR(64); 
DECLARE v_OPSTATE_D2 VARCHAR(64); 
DECLARE v_OPSTATE_D3 VARCHAR(64); 
DECLARE v_GEO_LOCATION VARCHAR(64); 
DECLARE v_GEO_AREA VARCHAR(64); 
DECLARE v_GEO_COORDINATES VARCHAR(64); 
DECLARE v_ACCESS VARCHAR(128);
DECLARE v_PRIORITY VARCHAR(32);
DECLARE v_BUSINESS_QUALIFIER1 VARCHAR(64);
DECLARE v_BUSINESS_QUALIFIER2 VARCHAR(64);
DECLARE v_BUSINESS_QUALIFIER3 VARCHAR(64);
DECLARE v_BUSINESS_QUALIFIER4 VARCHAR(64);
DECLARE v_cntd1l1 INTEGER ;
DECLARE v_cntd2l1 INTEGER ;
DECLARE v_cntd3l1 INTEGER ;
DECLARE v_count,v_numl3,v_commitcount INTEGER DEFAULT 0;

DECLARE c1 CURSOR WITH HOLD FOR 
  SELECT l3 from 
  (SELECT  l3 from  d2_l1 group by l3
   UNION SELECT  l3 from  d3_l1 group by l3
   UNION SELECT  l3 from  d1_l1 group by l3); 


SELECT COUNT(*) INTO v_numl3 from  
  (SELECT l3 from 
  (SELECT  l3 from  d2_l1 group by l3
   UNION SELECT  l3 from  d3_l1 group by l3
   UNION SELECT  l3 from  d1_l1 group by l3)) ;


 call DBMS_OUTPUT.PUT_LINE('Num L3 = ' || v_numl3);
OPEN c1;
WHILE v_count < v_numl3
DO
 SET v_cntd1l1 = 0;
 SET v_cntd2l1 = 0;
 SET v_cntd3l1 = 0;

 SET v_L3 = ''   ; 
 SET v_L3TYPE = ''    ; 
 SET v_REGION = ''    ; 
 SET v_L4 = ''    ; 
 SET v_OPSTATE_D1 = ''    ; 
 SET v_OPSTATE_D2 = ''    ; 
 SET v_OPSTATE_D3 = ''    ; 
 SET v_GEO_LOCATION = ''    ; 
 SET v_GEO_AREA = ''    ; 
 SET v_GEO_COORDINATES = ''    ; 
 SET v_ACCESS = ''    ;
 SET v_PRIORITY = ''    ;
 SET v_BUSINESS_QUALIFIER1 = ''    ;
 SET v_BUSINESS_QUALIFIER2 = ''    ;
 SET v_BUSINESS_QUALIFIER3 = ''    ;
 SET v_BUSINESS_QUALIFIER4 = ''    ;

 FETCH c1 INTO v_L3;

 SELECT COUNT(*) INTO v_cntd1l1 FROM (select l1 from d1_l1 WHERE l3 = v_l3 group by l1); 
 SELECT COUNT(*) INTO v_cntd2l1 FROM (select l1 from d2_l1 WHERE l3 = v_l3 group by l1); 
 SELECT COUNT(*) INTO v_cntd3l1 FROM (select l1 from d3_l1 WHERE l3 = v_l3 group by l1); 

 IF ((v_cntd1l1 > 0) and (v_cntd2l1 > 0) and (v_cntd3l1 > 0)) THEN SET v_l3type = 'D1D2D3'; END IF;
 IF ((v_cntd1l1 > 0) and (v_cntd2l1 > 0) and (v_cntd3l1 = 0)) THEN SET v_l3type = 'D1D2'; END IF;
 IF ((v_cntd1l1 > 0) and (v_cntd2l1 = 0) and (v_cntd3l1 > 0)) THEN SET v_l3type = 'D1D3'; END IF;
 IF ((v_cntd1l1 = 0) and (v_cntd2l1 > 0) and (v_cntd3l1 > 0)) THEN SET v_l3type = 'D2D3'; END IF;
 IF ((v_cntd1l1 > 0) and (v_cntd2l1 = 0) and (v_cntd3l1 = 0)) THEN SET v_l3type = 'D1only'; END IF;
 IF ((v_cntd1l1 = 0) and (v_cntd2l1 > 0) and (v_cntd3l1 = 0)) THEN SET v_l3type = 'D2only'; END IF;
 IF ((v_cntd1l1 = 0) and (v_cntd2l1 = 0) and (v_cntd3l1 > 0)) THEN SET v_l3type = 'D3only'; END IF;

 IF (v_cntd1l1 > 0) THEN
 SELECT OPSTATUS
 INTO   v_OPSTATE_D1 
 FROM d1_l1 WHERE L3 = v_L3 
 FETCH FIRST 1 ROWS ONLY;
 END IF;

 IF (v_cntd2l1 > 0) THEN
 SELECT OPSTATUS
 INTO   v_OPSTATE_D2 
 FROM d2_l1 WHERE L3 = v_L3 
 FETCH FIRST 1 ROWS ONLY;
 END IF;

 IF (v_cntd3l1 > 0) THEN
 SELECT OPSTATUS
 INTO   v_OPSTATE_D3 
 FROM d3_l1 WHERE L3 = v_L3 
 FETCH FIRST 1 ROWS ONLY;
 END IF;


 IF (v_cntd1l1 > 0) THEN
 SELECT REGION,GEO_LOCATION,GEO_AREA,GEO_COORDINATES,
        ACCESS,PRIORITY,
        QUAL1,QUAL2,QUAL3,QUAL4
 INTO   v_REGION,v_GEO_LOCATION,v_GEO_AREA,v_GEO_COORDINATES,
        v_ACCESS, v_PRIORITY, 
        v_BUSINESS_QUALIFIER1, v_BUSINESS_QUALIFIER2, v_BUSINESS_QUALIFIER3, v_BUSINESS_QUALIFIER4
 FROM d1_l1 WHERE L3 = v_L3 
 FETCH FIRST 1 ROWS ONLY;
 ELSEIF (v_cntd2l1 > 0) THEN
 SELECT REGION,GEO_LOCATION,GEO_AREA,GEO_COORDINATES,
        ACCESS,PRIORITY,
        QUAL1,QUAL2,QUAL3,QUAL4
 INTO   v_REGION,v_GEO_LOCATION,v_GEO_AREA,v_GEO_COORDINATES,
        v_ACCESS, v_PRIORITY, 
        v_BUSINESS_QUALIFIER1, v_BUSINESS_QUALIFIER2, v_BUSINESS_QUALIFIER3, v_BUSINESS_QUALIFIER4
 FROM d2_l1 WHERE L3 = v_L3 
 FETCH FIRST 1 ROWS ONLY;
 ELSEIF (v_cntd3l1 > 0) THEN
 SELECT REGION,GEO_LOCATION,GEO_AREA,GEO_COORDINATES,
        ACCESS,PRIORITY,
        QUAL1,QUAL2,QUAL3,QUAL4
 INTO   v_REGION,v_GEO_LOCATION,v_GEO_AREA,v_GEO_COORDINATES,
        v_ACCESS, v_PRIORITY, 
        v_BUSINESS_QUALIFIER1, v_BUSINESS_QUALIFIER2, v_BUSINESS_QUALIFIER3, v_BUSINESS_QUALIFIER4
 FROM d3_l1 WHERE L3 = v_L3 
 FETCH FIRST 1 ROWS ONLY;
 END IF;
 
 delete from L3_INFO where   l3 = v_l3 ; /* Clear any existing rows */

 insert into L3_INFO  (
 L3 , 
 L3TYPE , 
 REGION , 
 L4 , 
 OPSTATE_D1 , 
 OPSTATE_D2 , 
 OPSTATE_D3 , 
 GEO_LOCATION , 
 GEO_AREA , 
 GEO_COORDINATES , 
 ACCESS ,
 PRIORITY ,
 BUSINESS_QUALIFIER1 ,
 BUSINESS_QUALIFIER2 ,
 BUSINESS_QUALIFIER3 ,
 BUSINESS_QUALIFIER4 
 ) 
 values (
 v_L3 , 
 v_L3TYPE , 
 v_REGION , 
 v_L4 , 
 v_OPSTATE_D1 , 
 v_OPSTATE_D2 , 
 v_OPSTATE_D3 , 
 v_GEO_LOCATION , 
 v_GEO_AREA , 
 v_GEO_COORDINATES , 
 v_ACCESS ,
 v_PRIORITY ,
 v_BUSINESS_QUALIFIER1 ,
 v_BUSINESS_QUALIFIER2 ,
 v_BUSINESS_QUALIFIER3 ,
 v_BUSINESS_QUALIFIER4 
 ); 

set v_count = v_count + 1;
 set v_commitcount = v_commitcount + 1;
 IF (v_commitcount = 100) THEN
 commit work;
 set v_commitcount = 0;
 END IF;
END WHILE;
CLOSE C1; 

 call DBMS_OUTPUT.PUT_LINE('Count = ' || v_count);
END @


