#!/bin/sh
#
# status_tracker   Tracks the key policy and copies value to db & omnibus
#                      with hysteresis - waits until value persists for some time
#
# chkconfig: 2345 99 75
# description: 
#
BASE=/var/run
PID=$BASE/status_tracker.pid
LOG=$BASE/status_tracker.log
LOCKFILE=/var/lock/subsys/status_tracker
CMD='/root/tbsm-container-pattern/status_tracker/status_tracker.sh /root/tbsm-container-pattern/status_tracker root'
COMMAND="$CMD"

USR=user

status() {
    echo
    echo "==== Status"

    if [ -f $PID ]
    then
        echo
        echo "Pid file: $( cat $PID ) [$PID]"
        echo
        ps -ef | grep -v grep | grep $( cat $PID )
    else
        echo
        echo "No Pid file"
    fi
}

start() {
    if [ -f $PID ]
    then
        echo
        echo "Already started. PID: [$( cat $PID )]"
    else
        echo "==== Start"
        touch $PID
        touch $LOCKFILE
        if nohup $COMMAND >>$LOG 2>&1 &
        then echo $! >$PID
             echo "Done."
             echo "$(date '+%Y-%m-%d %X'): START" >>$LOG
        else echo "Error... "
             /bin/rm -f $PID
             /bin/rm -f $LOCKFILE
        fi
    fi
}

kill_cmd() {
    SIGNAL=""; MSG="Killing "
    while true
    do
        LIST=`ps -ef | grep -v grep | grep -E 'TBSM_policylogger_l3_overall |status_tracker.py' | awk '{print $2}'`
        if [ "$LIST" ]
        then
            echo; echo "$MSG $LIST" ; echo
            echo $LIST | xargs kill $SIGNAL
            sleep 2
            SIGNAL="-9" ; MSG="Killing $SIGNAL"
            if [ -f $PID ]
            then
                /bin/rm -f $PID
            fi
            if [ -f $LOCKFILE ]
            then
                /bin/rm -f $LOCKFILE
            fi
        else
            if [ -f $PID ]
            then
                /bin/rm $PID
            fi
            if [ -f $LOCKFILE ]
            then
                /bin/rm -f $LOCKFILE
            fi
           echo; echo "All killed..." ; echo
           break
        fi
    done
}

stop() {
    echo "==== Stop"

    if [ -f $PID ]
    then
        if kill $( cat $PID )
        then echo "Done."
             echo "$(date '+%Y-%m-%d %X'): STOP" >>$LOG
        fi
        /bin/rm $PID
        if [ -f $LOCKFILE ]
        then
          /bin/rm -f $LOCKFILE
        fi
        kill_cmd
    else
        echo "No pid file. Already stopped?"
    fi
}

case "$1" in
    'start')
            start
            ;;
    'stop')
            stop
            ;;
    'restart')
            stop ; echo "Sleeping..."; sleep 1 ;
            start
            ;;
    'status')
            status
            ;;
    *)
            echo
            echo "Usage: $0 { start | stop | restart | status }"
            echo
            exit 1
            ;;
esac

exit 0

